using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace _5413__ASP.NET.UI
{
    public partial class editarUtilizador : System.Web.UI.Page
    {
        protected DataSet ds;
        static int userID;
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                userID = int.Parse(Request.QueryString["id"]);
                preencheUtilizador(userID);
            }
        }//--------------------------------------------------------------------------

        protected void preencheUtilizador(int userID)
        {
            BLL.UtilizadorBLL b = new BLL.UtilizadorBLL();
            ds = b.obterUtilizador(userID);
            dtv_utilizador.DataSource = ds;
            dtv_utilizador.AllowPaging = true;
            dtv_utilizador.AutoGenerateEditButton = false;
            dtv_utilizador.AutoGenerateDeleteButton = false;
            dtv_utilizador.DataBind();
        }//--------------------------------------------------------------------------

        protected void dtv_utilizador_ModeChanging(object sender, DetailsViewModeEventArgs e)
        {
            if (e.CancelingEdit)
            {
                Response.Redirect("admindashboard.aspx");
            }
            if (dtv_utilizador.CurrentMode == DetailsViewMode.ReadOnly)
            {
                dtv_utilizador.ChangeMode(DetailsViewMode.Edit);
                preencheUtilizador(userID);
            }
            else if (dtv_utilizador.CurrentMode == DetailsViewMode.Edit)
            {
                dtv_utilizador.ChangeMode(DetailsViewMode.ReadOnly);
                preencheUtilizador(userID);
            }
        }//--------------------------------------------------------------------------

        protected void dtv_utilizador_ItemUpdating(object sender, DetailsViewUpdateEventArgs e)
        {
            L_Error.Visible = false;

            BLL.UtilizadorBLL b = new BLL.UtilizadorBLL();

            int userID = Convert.ToInt32(e.NewValues[0].ToString()); 
            int admin = 0;
            if (e.NewValues[5].ToString() == "True")
                admin = 1;

            if (b.contaAdmins() <1 && admin == 0)
            {
                L_Error.Visible = true;
                L_Error.Text = "TEM DE HAVER UM ADMIN";
                return;
            }

            string nome = e.NewValues[1].ToString();
            string email = e.NewValues[2].ToString();
            string password = e.NewValues[3].ToString();
            int verificado = 0;
            if (e.NewValues[4].ToString() == "True")
                verificado = 1;
            

            b.editarUtilizador(userID, nome, email, password, verificado, admin);

            dtv_utilizador.ChangeMode(DetailsViewMode.ReadOnly);
            Response.Redirect("admindashboard.aspx");
        }//--------------------------------------------------------------------------
    }
}